In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Landfill map data

In [12]:
df = pd.read_csv("/Users/mattiesanseverino/Downloads/landfills_xy.csv")
info = pd.read_csv("/Users/mattiesanseverino/Downloads/landfill_info.csv")

In [13]:
grouped_df = df.groupby('SWIS').agg({'Longitude (Decimal Degrees)': list, 'Latitude (Decimal Degrees)': list}).reset_index()

In [14]:
joined_df = pd.merge(grouped_df, info, on='SWIS', how='outer')
joined_df.head()

,SWIS,Longitude (Decimal Degrees),Latitude (Decimal Degrees),Landfill Name,Latitude,Longitude,Physical Address,City,State,Zip,...,Year Range if not Exact,Waste in Place (Tons),Converted,Conversion Type,Site Conversion,Site Regulartory Status,Documentation Name,Documentation Link,Documentation Site,SWIS Documentation
0,01-AA-0001,"[122.086476, 122.08398170000001, 122.082102900...","[37.581434200000004, 37.5767105, 37.5769416000...",Turk Island Land,37.5786,-122.0858,32505 Union City Boulevard,Union City,CA,94587.0,...,This landfill consisted of three separate parc...,NaN,Not Converted,NaN,NaN,Surrendered,Post Closure Land Use Proposal and Work Plan -...,https://secure.calrecycle.ca.gov/SWISDocument/...,Cal Recycle,https://www2.calrecycle.ca.gov/SolidWaste/Site...
1,01-AA-0006,"[122.1967746, 122.19372959999998, 122.19146210...","[37.713497499999995, 37.7090385, 37.7043999, 3...",Davis Street Sanitary Landfill,37.7144,-122.1948,W End of Davis Street,San Leandro,CA,94577.0,...,NaN,NaN,Fully Converted,Public,Oyster Bay Regional Park,Permitted,Focused Feasibility Study Leachate Management,https://secure.calrecycle.ca.gov/SWISDocument/...,Cal Recycle,https://www2.calrecycle.ca.gov/SolidWaste/Site...
2,01-AA-0008,"[121.99635959999999, 121.988295, 121.991694999...","[37.498418799999996, 37.4908525, 37.488385, 37...",Tri Cities Recycling & Disposal,37.4928,-121.9923,7010 Auto Mall Pkwy,Fremont,CA,94538.0,...,NaN,NaN,Not Converted,NaN,NaN,Permitted,Final Closure/Post-Closure Maintenance Plan,https://secure.calrecycle.ca.gov/SWISDocument/...,Cal Recycle,https://www2.calrecycle.ca.gov/SolidWaste/Site...
3,01-AA-0011,"[122.3119327, 122.3150361, 122.316125, 122.317...","[37.890025200000004, 37.889509600000004, 37.88...",Albany Landfill,37.8898,-122.3113,W End Buchanan St.,Albany,CA,94706.0,...,Reports say the dump opened in 1963 but the Ci...,NaN,Fully Converted,Public,Albany Bulb,Permitted,NaN,NaN,NaN,https://www2.calrecycle.ca.gov/SolidWaste/Site...
4,01-AA-0012,"[122.2267763, 122.2267317, 122.22813670000001,...","[37.7480251, 37.745512299999994, 37.7455122999...",City Of Alameda SW II-2 Disposal Site / Doolit...,37.7470,-122.2340,N Side Doolittle Dr @ Br To Alameda Isl.,Alameda,CA,94502.0,...,NaN,NaN,Not Converted,NaN,NaN,Permitted,NaN,NaN,NaN,https://www2.calrecycle.ca.gov/SolidWaste/Site...

In [15]:

#joined_df['SWIS'] = grouped_df['SWIS'].apply(lambda x: f'"{x}"')
#joined_df['Longitude (Decimal Degrees)'] = grouped_df['Longitude (Decimal Degrees)'].apply(lambda x: f'"{x}"')
#joined_df['Latitude (Decimal Degrees)'] = grouped_df['Latitude (Decimal Degrees)'].apply(lambda x: f'"{x}"')
for col in joined_df.columns:
    joined_df[col] = joined_df[col].apply(lambda x: f'"{x}"')
final_df = joined_df[['SWIS', 'Longitude (Decimal Degrees)', 'Latitude (Decimal Degrees)', 'Landfill Name', 'City', 'Landfill Ownership Type', 'Owner', 'Class', 'Type of Waste', 'Type of Waste 2 (Supporting Info)', 'Current Landfill Status', 'Year Opened', 'Year Closed', 'Year Range if not Exact', 'Converted', 'Conversion Type', 'Site Conversion ', 'Site Regulartory Status', 'Documentation Link']]

### Download csv

In [21]:
#final_df.to_csv('grouped_xy_with_info.csv', index=False)

# Class data

In [17]:
# Count the number of True and False per name
counts = final_df['Class'].value_counts()
print(counts)

"nan"                               69
"Class III"                         59
"Class I"                           14
"Class II"                          12
"Class I/Class II"                   3
"Class I / Class III"                1
"Class II / Class III"               1
"Class II/Class III"                 1
"Class I / Class II / Class III"     1
"Inert Waste/Class III"              1
Name: Class, dtype: int64

In [18]:
#counts.to_csv('class_counts.csv')

# Ownership data

In [19]:
ownership_counts = final_df['Landfill Ownership Type'].value_counts()
print(ownership_counts)

"Private"           71
"Public"            55
"nan"               30
"Public/Private"     5
"Private/Public"     1
Name: Landfill Ownership Type, dtype: int64

In [20]:
ownership_counts.to_csv('ownership_counts.csv')

# Census data

In [22]:
data = pd.read_csv("/Users/mattiesanseverino/Downloads/CensusData_PovertyStatus.xlsx - Sheet1.csv")

In [23]:
data.head()

,OBJECTID,the_geom,objectid_1,statefp,countyfp,trctce,geoid,name_,namelsad,mtfcc,...,Shape__Length,Geographic_Area_Name,Census_Tracts,County,State,estimatedPercentBelowPovertyLevel,Estimate Percent below poverty level Black or African American,Estimate Percent Below poverty level White Alone,Estimate Percent below poverty level Asian Alone,Estimate Percent below poverty level Hispanic of Latino Origin
0,89,"[-122.459192171, 37.785686985, -122.458075171,...",746,6,75,NaN,6075015402,154.02,Census Tract 154.02,G5020,...,0.035186,Census Tract 154.02,154.02,San Francisco County,California,0.00%,0.00%,0.00%,0.00%,0.00%
1,136,"[-122.44613017, 37.791003986, -122.444491169, ...",814,6,75,NaN,6075013402,134.02,Census Tract 134.02,G5020,...,0.017228,Census Tract 134.02,134.02,San Francisco County,California,0.00%,0.00%,0.00%,0.00%,0.00%
2,288,"[-122.111688087, 37.510412986, -122.111653087,...",901,6,1,NaN,6001444303,4443.03,Census Tract 4443.03,G5020,...,0.155013,Census Tract 4443.03,4443.03,Alameda County,California,0.00%,0.00%,0.00%,0.00%,0.00%
3,308,"[-122.499192195, 37.942284995, -122.498924196,...",668,6,41,NaN,6041122000,1220.00,Census Tract 1220,G5020,...,0.041972,Census Tract 1220,1220.00,Marin County,California,0.00%,0.00%,0.00%,0.00%,0.00%
4,318,"[-122.510649179, 37.782127981, -122.510519179,...",527,6,75,NaN,6075980200,9802.00,Census Tract 9802,G5020,...,0.057758,Census Tract 9802,9802.00,San Francisco County,California,0.00%,0.00%,0.00%,0.00%,0.00%

In [30]:
simple_data = data[["the_geom", "Geographic_Area_Name", "estimatedPercentBelowPovertyLevel"]]
simple_data.head()

,the_geom,Geographic_Area_Name,estimatedPercentBelowPovertyLevel
0,"[-122.459192171, 37.785686985, -122.458075171,...",Census Tract 154.02,0.00%
1,"[-122.44613017, 37.791003986, -122.444491169, ...",Census Tract 134.02,0.00%
2,"[-122.111688087, 37.510412986, -122.111653087,...",Census Tract 4443.03,0.00%
3,"[-122.499192195, 37.942284995, -122.498924196,...",Census Tract 1220,0.00%
4,"[-122.510649179, 37.782127981, -122.510519179,...",Census Tract 9802,0.00%

In [31]:
simple_data.to_csv('census_data.csv')